services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
  backend:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/hlow_chat
