apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inchat-prod
resources:
  - ../../base
images:
  - name: ghcr.io/your-org/inchat-api
    newTag: prod
replicas:
  - name: inchat-api
    count: 3
